/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab_3;

/**
 *
 * @author Administrator
 */
public class lab3_2 extends javax.swing.JFrame {

    /**
     * Creates new form lab3_2
     */
    public lab3_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        MenuKiemTraIP1 = new javax.swing.JCheckBoxMenuItem();
        MenuTimIPCuaTenMien = new javax.swing.JCheckBoxMenuItem();
        MenuTimTenMienCuaIP = new javax.swing.JCheckBoxMenuItem();
        MenuTimIPCuaMayCucBo = new javax.swing.JCheckBoxMenuItem();
        MenuKiemTraIP2 = new javax.swing.JCheckBoxMenuItem();
        MenuKiemTra2TenMien = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thực hành lập trình mạng");

        jMenu1.setText("Hệ thống");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Chức năng");

        MenuKiemTraIP1.setSelected(true);
        MenuKiemTraIP1.setText("Kiểm tra IP");
        MenuKiemTraIP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuKiemTraIP1ActionPerformed(evt);
            }
        });
        jMenu2.add(MenuKiemTraIP1);

        MenuTimIPCuaTenMien.setSelected(true);
        MenuTimIPCuaTenMien.setText("Tìm IP của tên miền");
        MenuTimIPCuaTenMien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTimIPCuaTenMienActionPerformed(evt);
            }
        });
        jMenu2.add(MenuTimIPCuaTenMien);

        MenuTimTenMienCuaIP.setSelected(true);
        MenuTimTenMienCuaIP.setText("Tìm tên miền của IP");
        MenuTimTenMienCuaIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTimTenMienCuaIPActionPerformed(evt);
            }
        });
        jMenu2.add(MenuTimTenMienCuaIP);

        MenuTimIPCuaMayCucBo.setSelected(true);
        MenuTimIPCuaMayCucBo.setText("Tìm IP của máy cục bộ");
        MenuTimIPCuaMayCucBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTimIPCuaMayCucBoActionPerformed(evt);
            }
        });
        jMenu2.add(MenuTimIPCuaMayCucBo);

        MenuKiemTraIP2.setSelected(true);
        MenuKiemTraIP2.setText("Kiểm tra IP");
        MenuKiemTraIP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuKiemTraIP2ActionPerformed(evt);
            }
        });
        jMenu2.add(MenuKiemTraIP2);

        MenuKiemTra2TenMien.setSelected(true);
        MenuKiemTra2TenMien.setText("Kiểm tra 2 tên miền");
        MenuKiemTra2TenMien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuKiemTra2TenMienActionPerformed(evt);
            }
        });
        jMenu2.add(MenuKiemTra2TenMien);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuKiemTra2TenMienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuKiemTra2TenMienActionPerformed
        // TODO add your handling code here:
        lab3_2_6 obj = new lab3_2_6();
        obj.setVisible(true); 
    }//GEN-LAST:event_MenuKiemTra2TenMienActionPerformed

    private void MenuKiemTraIP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuKiemTraIP2ActionPerformed
        // TODO add your handling code here:
        lab3_2_5 obj = new lab3_2_5();
        obj.setVisible(true); 
    }//GEN-LAST:event_MenuKiemTraIP2ActionPerformed

    private void MenuTimIPCuaMayCucBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTimIPCuaMayCucBoActionPerformed
        // TODO add your handling code here:
        lab3_2_4 obj = new lab3_2_4();
        obj.setVisible(true); 
    }//GEN-LAST:event_MenuTimIPCuaMayCucBoActionPerformed

    private void MenuTimTenMienCuaIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTimTenMienCuaIPActionPerformed
        // TODO add your handling code here:
        lab3_2_3 obj = new lab3_2_3();
        obj.setVisible(true); 
    }//GEN-LAST:event_MenuTimTenMienCuaIPActionPerformed

    private void MenuTimIPCuaTenMienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTimIPCuaTenMienActionPerformed
        // TODO add your handling code here:
        lab3_2_2 obj = new lab3_2_2();
        obj.setVisible(true); 
    }//GEN-LAST:event_MenuTimIPCuaTenMienActionPerformed

    private void MenuKiemTraIP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuKiemTraIP1ActionPerformed
        // TODO add your handling code here:
        lab3_2_1 obj = new lab3_2_1();
        obj.setVisible(true); 
    }//GEN-LAST:event_MenuKiemTraIP1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lab3_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lab3_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lab3_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lab3_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lab3_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem MenuKiemTra2TenMien;
    private javax.swing.JCheckBoxMenuItem MenuKiemTraIP1;
    private javax.swing.JCheckBoxMenuItem MenuKiemTraIP2;
    private javax.swing.JCheckBoxMenuItem MenuTimIPCuaMayCucBo;
    private javax.swing.JCheckBoxMenuItem MenuTimIPCuaTenMien;
    private javax.swing.JCheckBoxMenuItem MenuTimTenMienCuaIP;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
